spring:
  datasource:
    #url: jdbc:mariadb://localhost:3306/board
    #username: root
    #password: 1234
    #driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true
